[colors.bright]
black = "0x3f3951"
blue = "0xb1baf4"
cyan = "0xb3f4f3"
green = "0xb1f2a7"
magenta = "0xe192ef"
red = "0xe965a5"
white = "0xeee9fc"
yellow = "0xebde76"

[colors.cursor]
cursor = "0xeee9fc"
text = "0xeee9fc"

[colors.normal]
black = "0x282433"
blue = "0xb1baf4"
cyan = "0xb3f4f3"
green = "0xb1f2a7"
magenta = "0xe192ef"
red = "0xe965a5"
white = "0xeee9fc"
yellow = "0xebde76"

[colors.primary]
background = "0x282433"
foreground = "0xeee9fc"

[cursor.style]
shape = "Beam"


# [font.bold]
# family = "CaskaydiaCove Nerd Font"
# style = "Light"
#
# [font.bold_italic]
# family = "CaskaydiaCove Nerd Font"
# style = "LightItalic"
#
# [font.italic]
# family = "CaskaydiaCove Nerd Font"
# style = "LightItalic"
#
# [font.normal]
# family = "CaskaydiaCove Nerd Font"
# style = "Light"

[font]
size = 17
bold = { family = "CaskaydiaCove Nerd Font", style = "Light"}
bold_italic = { family = "CaskaydiaCove Nerd Font", style = "LightItalic"}
italic = { family = "CaskaydiaCove Nerd Font", style = "LightItalic"}
normal = { family = "CaskaydiaCove Nerd Font", style = "Light"}


# [font.bold]
# family = "BerkeleyMono Nerd Font"
# style = "Regular"
#
# [font.bold_italic]
# family = "BerkeleyMono Nerd Font"
# style = "Italic"
#
# [font.italic]
# family = "BerkeleyMono Nerd Font"
# style = "Italic"
#
# [font.normal]
# family = "BerkeleyMono Nerd Font"
# style = "Regular"

[keyboard]
bindings = [
    { key = "F", mods = "Alt", chars = "\u001Bf"},
    { key = "B", mods = "Alt", chars = "\u001Bv"},
    { key = "V", mods = "Alt", chars = "\u001Bv"},
    { key = "P", mods = "Alt", chars = "\u001Bp"},
    { key = "D", mods = "Alt", chars = "\u001Bd"},
    { key = "LBracket", mods = "Alt", chars = "\u001B["},
    { key = "RBracket", mods = "Alt", chars = "\u001B]"},
    { key = "1", mods = "Alt", chars = "\u001B1"},
    { key = "2", mods = "Alt", chars = "\u001B2"},
    { key = "3", mods = "Alt", chars = "\u001B3"},
    { key = "4", mods = "Alt", chars = "\u001B4"},
    { key = "5", mods = "Alt", chars = "\u001B5"},
]

# [[keyboard.bindings]]
# chars = "\u001Bf"
# key = "F"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bb"
# key = "B"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bv"
# key = "V"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bp"
# key = "P"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bd"
# key = "D"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001B["
# key = "LBracket"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001B]"
# key = "RBracket"
# mods = "Alt"

[window]
startup_mode = "Fullscreen"
