# Colors (Nord light) theme based on https//github.com/nordtheme/alacritty/issues/28#issuecomment-1422225211

# Default colors
[colors.primary]
background = '#ECEFF4'
foreground = '#81A1C1'

# Normal colors
[colors.normal]
black   = '#D8DEE9'
red     = '#bf616a'
green   = '#a3be8c'
yellow  = '#D08770'
blue    = '#81A1C1'
magenta = '#B48EAD'
cyan    = '#88C0D0'
white   = '#4C566A'

# Bright colors
[colors.bright]
black   = '#D8DEE9'
red     = '#bf616a'
green   = '#a3be8c'
yellow  = '#D08770'
blue    = '#D8DEE9'
magenta = '#B48EAD'
cyan    = '#8FBCBB'
white   = '#D8DEE9'

[cursor.style]
shape = "Beam"

[font]
size = 13
bold = { family = "MonoLisa Nerd Font", style = "Bold"}
bold_italic = { family = "MonoLisa Nerd Font", style = "BoldItalic"}
italic = { family = "MonoLisa Nerd Font", style = "Italic"}
normal = { family = "MonoLisa Nerd Font", style = "Regular"}

# bold = { family = "CaskaydiaCove Nerd Font", style = "SemiLight"}
# bold_italic = { family = "CaskaydiaCove Nerd Font", style = "SemiLight Italic"}
# italic = { family = "CaskaydiaCove Nerd Font", style = "SemiLight Italic"}
# normal = { family = "CaskaydiaCove Nerd Font", style = "SemiLight"}

[keyboard]
bindings = [
    { key = "F", mods = "Alt", chars = "\u001Bf"},
    { key = "B", mods = "Alt", chars = "\u001Bb"},
    { key = "V", mods = "Alt", chars = "\u001Bv"},
    { key = "P", mods = "Alt", chars = "\u001Bp"},
    { key = "D", mods = "Alt", chars = "\u001Bd"},
    { key = "LBracket", mods = "Alt", chars = "\u001B["},
    { key = "RBracket", mods = "Alt", chars = "\u001B]"},
    { key = "1", mods = "Alt", chars = "\u001B1"},
    { key = "2", mods = "Alt", chars = "\u001B2"},
    { key = "3", mods = "Alt", chars = "\u001B3"},
    { key = "4", mods = "Alt", chars = "\u001B4"},
    { key = "5", mods = "Alt", chars = "\u001B5"},
]

[window]
startup_mode = "Fullscreen"